version: 1.4.0
description: "Rock mask creation using YOLO and SAM"

# Model initialization
model_confidence_threshold: 0.65
iou_threshold: 0.25
sahi: True
model_type: "rtdetr"
model_path: "/repo/Data/best.pt"
sam_model_path: "mobile_sam.pt"