version: '3'

services:
  algorithm:
    build: .
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - MEDIA_ID=${MEDIA_ID}
      - HOST=${HOST}
      - TOKEN=${TOKEN}
      - START_AT=${START_AT}
      - END_AT=${END_AT}
      - CONFIDENCE=${CONFIDENCE}
      - IOU=${IOU}
      - DEBUG=${DEBUG}
    volumes:
      - "./Data/:/workdir/Data/"